apiVersion: ENC[AES256_GCM,data:a0c=,iv:6MPLm+hvZm7ODPy1cnWdRZxEHzHBr5MSdqGgE+BT/Gk=,tag:wHlv7VfqO36ZjOQ5StgT/g==,type:str]
kind: ENC[AES256_GCM,data:nNMxzVVT,iv:76PnCEA7xa6t3AUzRToFva7eRyRxECMk+jT9cdeCsJQ=,tag:QvXUX2assmUFwvD1G6fPfA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:w+fFbswze5NFyFyQAF+k,iv:UM8nfcJUO5pUtb6DUSE/eIzRCllMMbCgm6Vnmys7pmk=,tag:zzVUnIAjQHwNXmRMkYEfrA==,type:str]
    namespace: ENC[AES256_GCM,data:iJw3ow7mpFAt,iv:WeZjdxbP2MijI3MBE5yfcxbeDJDeT2sI0FIQLQYeC1g=,tag:w6iLSSWl+c7F40wzktmJbQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:ugl3mlc=,iv:tBlPTehZBgGbmvhLk7SJHXx1aCcczv5ialmWfvV9Fjk=,tag:LeC2Ck5gHvTWVMuxTWtCew==,type:str]
    password: ENC[AES256_GCM,data:VAljWwiRLM6gWQXTb9U=,iv:dOzEEPE91ALhHEeG8QmIJfUrwNqYj1uvxNLkuS64DCk=,tag:VCbt7UN/zLQbiJGUF57wTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWTRsaGJFM1B3NkJhSVpa
            cyt6dFZOcEVyZDZxNzU4TVNQR0xtSitFdnhvCkJPV3ZxaWdjZngwT00zS0tYWGs1
            TnJLZ2NqWU1Zc2NzR0lQVjBxM0l2ZlkKLS0tIFdDdGEzY2hsN2VtbkxMMzhaOVRq
            VEZycVhPcXJqSUtXMGtOWVBIUG8vbEEKVYHEpY8t4UGATFdfpjUykZ7X618UTEUQ
            cUUfq3wrv8++CCzmrSt1sTxtL1NwhgY9F79RlJ7zbIDCTKwBWdWT3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x567hflvyf6w6vt0ynsh36lsckdyp5mufjrz8ndjn7g3kwugrcest2afmt
    lastmodified: "2026-08-25T13:19:54Z"
    mac: ENC[AES256_GCM,data:ZLf1arFrTOAQkh1QowJGeQhmtRlmLMBjdJdhLJWhtsW81ELxDfUaeSXjEro8SypFeWGT3U1xsyXDPDrx2JGK+/dnsuvM0aKxtenJsBlVZMy8QkrCxAEZ8vISoAfFHOFs/Hi4erMS7s4OUQ4Wuw4UKxJS+fElRcSBTr+NJ0L1aHM=,iv:do62gErf+1TH+jAOSmm0TcxgsgzUel4LKl7ezv1buFY=,tag:A5ESpSldyLn7h+SH7vt3PQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
