apiVersion: ENC[AES256_GCM,data:4E0=,iv:l6dh6CZYDCj1LQdTEfDUTnrI5IurUMopblcKyagN38c=,tag:i4U71gxred77UxHewaQ4+A==,type:str]
kind: ENC[AES256_GCM,data:EZxhuDuP,iv:w/fndb0ofFQPfKg8msySvE3TrVVmOcwkFoqdJxJTPxc=,tag:hYY0JlSigzND7unLmFrxfA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QrqqV03FHzC/ly4BqJ6CIYM=,iv:pAOxAd56goC41yoj1lio2TvjNpdPWUDw9+lOo6zJO6Q=,tag:Gh9p4ihraN8joWiwf/D0Rg==,type:str]
    namespace: ENC[AES256_GCM,data:0PuLP1eIhWHV,iv:/JEy0jVXcPGYJxWzYsKM06YoZQ138Fv6Jf0jJwdP2L4=,tag:1XfuraBfcQj5g/rQcdDFuA==,type:str]
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:OG6DhHffBjT6DCkZWSF+xbrmUaJvoyhaKAm73rSZMhZ35gLpZ1E0xgKpqSIIIZIiRHcKRCdHZT52A4fe2k2R2CBKwTH+18TL,iv:dV3lJU/p0hbzfgcNcKyzm71ZZg/IxGrTglpYImKb8ws=,tag:LEOJHexk9No0Ujv0661Ysg==,type:str]
    DISCORD_APP_ID: ENC[AES256_GCM,data:+Xek4/ppMpNiP+vWXbmAb2zZ/w==,iv:2c5n9BH7YZYD5eWeWvJcOT87Bl0Wxc+9rbbOUiAgUww=,tag:PZ3e944aayyMQM02DvTe5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidFRDRzdJcVA5Ujd4dHdv
            TGNxaDlkY2NnMmVKbWw3R29UYWl5cktUTHk4CjJ6UXQ2L1kxSGd4cVdKVUpQVXU3
            RzVkRFdpTnV0NzFEOVdDVTYvQU9XbUUKLS0tIDJxUDVHSlR3SGpOZW9UNXQ0ZVBn
            Skk2bm5nY3lqbnkvUEtyZ1gvL2J2WWcKf/O05qPt+GuZJVfq9iNc+IAulPY2+FHN
            14IlW8FbrCxse5nqQZAyjKENlPQhkzKsEO1JdQA8CCd6xMOnHpxJUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x567hflvyf6w6vt0ynsh36lsckdyp5mufjrz8ndjn7g3kwugrcest2afmt
    lastmodified: "2026-09-11T09:41:50Z"
    mac: ENC[AES256_GCM,data:9iNfw0Xe363Qa8JmCebe3v+bbhOZ85JiNtIry7UYhNe2/0hN6zlyrFY1I/01jU2malFYdmmBlOv1bjhn26l40Oby/WP8JDwRlePmoOAyWHnbJsTbiVgeurjjttC8LaUMDd/DzxS37ef5WA43VVYqqFvZHB1Yyc5p0hXeDB/bMUI=,iv:6/HTFnaFAxa9ZSUsA8E2/YXvssrRyQzErwwAxNOQgQw=,tag:Ff5BgFNsrT8luXELHQpolg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
