apiVersion: ENC[AES256_GCM,data:La8=,iv:D4i9ggztrr4nnH+eJ+ED33Ufcg0n3GKHvdT+892LYi8=,tag:Qc9l3tF3ojn8kwyxh63ieg==,type:str]
kind: ENC[AES256_GCM,data:0klZvbyB,iv:trJfCpWdkknFYl8z6y00jc+TJpEcRcIPuOfJlm3iT88=,tag:oifoZ+ZweZ5JgJw2UNjhwA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Bz2Dg8VUVsE/abv0LozaHcM=,iv:3jaXpRLgjtX1xnN/8K3wSEfv06NHX96vgW9dHgjo0uc=,tag:WbcVROwoiF3ibfM5KYThfQ==,type:str]
    namespace: ENC[AES256_GCM,data:EcHkiG5Ex6w6,iv:yoWntE1UMuvo/Mi04VR0OpgPXdya2BpRIxtp2wkknrA=,tag:MMkyyGz+xww7VEq2MyeSKA==,type:str]
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:Z9fy83KxgJ7EeY3g6eAeW2uWO8CxEpAP4TMWxJFiG5Y=,iv:Gr1eQnHe2hRXBJ0I4lk8atWPlJ3Yx6XAK4qEsVBm/k8=,tag:qa6oITS/ZKJafk8t7DhW8Q==,type:str]
    DISCORD_APP_ID: ENC[AES256_GCM,data:oDpfOkhJ+MdJBOcmIDdN2iLGfQ==,iv:bZ/ai1lS0arleRvUx4Jtf5xBcTZXoGaTcSvyvyhaVeU=,tag:K4e4TFr0A0l7KhPCHfG2JA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TUV1b3d0SnJveUpMLzlD
            Y0Q3U2tvc3B2SUdnakdnbCsxNURjOFE0UjJNCnFXWitPbGRVV0ZLYWpmTllSQnhl
            RXRXdVhMck9pWHl5SG8wSUMwRWFpVkkKLS0tIGJHeGJlQWo4elFndVNkTHAwZVY0
            aXRBalNWQkpTYXYzN1hjQ1dMZVJKQ0kKChSBUSG0/YiN/FMdanWJzfBKynGq7lB8
            fp7zV+7yvfAv3g0boO1fdn7M9SO/csOCJiqFHMghuhdRCsKOr6AyLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x567hflvyf6w6vt0ynsh36lsckdyp5mufjrz8ndjn7g3kwugrcest2afmt
    lastmodified: "2026-09-11T09:21:55Z"
    mac: ENC[AES256_GCM,data:H0y55FCgVI8+dl61IZX8ahETvyXRtOgjMIKTITZFbSu0eC0g06u0COUxlL1Mp9+8KIQ+9MwU/MdERAD4BdjfBGJHdeHf6CbbClikSWUN0YKG4FOtbKG4ED/srGdf6270KJJGzy6foYSd3f9/0MjQ3xeXFokE91x2sYHTkaYEKyo=,iv:Pz76CxLu89IhNl1/BU1/FCkV9b9ENZho/pEarL5bS5g=,tag:ACL6vgD+ZF0+ILlo5E+Hug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
