apiVersion: ENC[AES256_GCM,data:Jlw=,iv:37W05goK2ehiihjATwEIOm/GfAYiVe4UC2HgS5DP7y4=,tag:3OhKq10mREwaNVq4L5iAXw==,type:str]
kind: ENC[AES256_GCM,data:lw2h16vc,iv:kxnW3tmG/xEnasxdjJoO+/XRrd+Q5sKYYsE8gYTGDN8=,tag:TWYw0qgAEWApgBoaqXA6Zw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GekZWgNLWnpVv1jpOf7XUS+ViOqCoHwukCnQ58vK,iv:bsRFj8ojR0bY+31szCjnM7hQOklovDCjZrrna63YT/A=,tag:iVVKaLi93cMhNFHreMO3zg==,type:str]
    namespace: ENC[AES256_GCM,data:axXjZxLH4RU=,iv:ITomT7B7mPvbtIedMOgXcRxARoLZE5T6bEjzK9qlLBw=,tag:b2HKVUZjyNw/shMaFBnK9w==,type:str]
stringData:
    username: ENC[AES256_GCM,data:zjdlDFE=,iv:eWDMz6Zgv3rk9BMcI98EhYpJAyO8QFOz/VpENvD/JXk=,tag:WmLRD/H8TLpdARYdwMZ2AQ==,type:str]
    password: ENC[AES256_GCM,data:bRJ7zHZVlzMeMYLnE70=,iv:TBJOHgPnl3mvcAU1JlYBjkxv0bvbEv5jzJswyoEAgyg=,tag:UHlQMol6CLf0HXlUyhphHQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUUFub0pLVFpYcUlPUi9m
            djNHYkxNaS9odWxwR1o4ME9WWEMvdTRBTGkwCnBtZkw2MHZQYTBNR2tMUDBZb0hO
            WUV5aFJmVjBPMzJua0JGSlVTNENydVEKLS0tIGlXcGhIQ0hTR2EwMVUrWnBuSHF6
            cWpuR3h4cUdsU0FHK1lLZXRoUWNJR2MKSeOYy3gc1S7NHywZqcLTw3rIKXmVEpvx
            8F86oOAzQ1HHB369LIMydhGKc9BNxBrNx5x4iiTk5XdBWaRrvYMw5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x567hflvyf6w6vt0ynsh36lsckdyp5mufjrz8ndjn7g3kwugrcest2afmt
    lastmodified: "2026-08-29T14:27:51Z"
    mac: ENC[AES256_GCM,data:KS57gaRlbJgoc3nUXSP/FqQJNRh3a3pSOActv5gETISesGKgKyvqgAXWs3rzNEUvQ0GUZT9QvaS33fEWw4gaEmDFMowHyhqYfjRhdiAG5Y7U+yRSHZp8qpUs/2GlxjBYx7EV7hej1GTZG2j2CbqaGLVcE3ghgqzPXPSydUyJVDE=,iv:8CH8tcgjcA0mZ+Wkw0hjSB0ZLCPo/RdAgcUgfitxJXY=,tag:2MXoPAMgc2j9BGYp1ftQzQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
