apiVersion: ENC[AES256_GCM,data:7Bo=,iv:8KlYM5QVcTKK1XHigm0sXCx3OUxb5EKoEdGDGnSJF3Y=,tag:Lk8ab9cIEgeHrr4QJiF+jQ==,type:str]
kind: ENC[AES256_GCM,data:PlpMyBl7,iv:rTTlwgm5x4PH4MKJpCt2ft9l6n6Im414ROhiHWV//ic=,tag:76+NndRvAlkezYyOCFsyGw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BMJpO+jURFtcUHfP1/pNfTVAfFL4ZnY=,iv:QPRaRm2WGUr5Ff9KlAtPybAwlO/atBhpCjEOirLLMec=,tag:Hh6W6CAs8hOupiTnh1KECw==,type:str]
    namespace: ENC[AES256_GCM,data:BYKpMANr4MSRTw==,iv:hkVqv0h4y4bdRfdFqSezwgi8VGzgPyT2YGGmcOhESgs=,tag:3qdShHmUw37hgTrX0NMKDw==,type:str]
stringData:
    .htpasswd: ENC[AES256_GCM,data:8d2WFvmwMzSIvcFNjdU+UuO66Jsgm8HZ05aDjrcZHWpnd9D7OSRbbBX0RA==,iv:QJ6hSS7Otni3VQs3cqMG7Rmbh/m0k/PManP0gN+27xk=,tag:/GO2LRJOf7eNuJHwghV7Hw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRWFhNzJhZDJzdUs1Z2lN
            WlY2clF6TkR3UDRiNmNROWVHTS9oZkFWalZvCmtET3FZWmREWm5yenJ1VHplTzFq
            WExGZTRkSzhsVzN6eFhKN1hpNEtzNnMKLS0tIDYvdzhFNE0xVXZFNVN2VnJCRUI2
            Q29nb0NCRTVjcGNDOTIzdjVtTlQ3Z3MKPBbQvOGdn1AuhW6yIxVOEoGHFaRw3YrQ
            Frwx35DjeJnKlMPQuKgJ4P8FZdZqbHT/tOypXE3/7XPQml73IrdfqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x567hflvyf6w6vt0ynsh36lsckdyp5mufjrz8ndjn7g3kwugrcest2afmt
    lastmodified: "2026-08-28T13:19:39Z"
    mac: ENC[AES256_GCM,data:OT7cTN9oWsqHEJILfFtYCflY9d94HuAUS+VaAMkTqPS/r7Q1eGVcWu7mUzslme/6p5oiZ0rMTFBag28ee08sXmjcVhW3uxulV6BEudEjdmXC1RAcBDiqjdggtXzwqtx285W/msnY9fFBQoiLj6j3uLfopHiKwOdIqK+D50nqDqU=,iv:xYlEkk7zoSKA8RMUzafjohtXv58LiZ8oIO3oV56wKiA=,tag:NKuotRWWyi7HXDrBhQlt8w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
