apiVersion: ENC[AES256_GCM,data:zyc=,iv:ZZ/8f5FShRiTd3XB22gSbhyVYUeTufQsKAaIhcyuM8M=,tag:C/wuhk3rlgupVJgAbW2jkw==,type:str]
kind: ENC[AES256_GCM,data:8/yJ2Wkz,iv:J/JyYRRD8VlTVLnkoeJXGmIWDN/eyVgTZm8xxFp/jLM=,tag:4PqrR5C8uzJWTjsJ2QLbLA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bLO2oOsXuW1FbuOrTfjzfgYUyL2+7MI=,iv:9fPYLYlHw8BycvZ+xOVJeFmPNOOpsd0zq3ozPYA5Nmw=,tag:IpMdWHcBOxjO9OWuyXrV7Q==,type:str]
    namespace: ENC[AES256_GCM,data:sm+2xJfCTGrfaA==,iv:eYKsr7XVk8jcmP85pmvuz4qBPUnBXoipUCPRKaRzr20=,tag:bL1waj+gVzbyNCQWCSu0HQ==,type:str]
stringData:
    .htpasswd: ENC[AES256_GCM,data:yCntpr9tEcXnmXtHKJDew9fIBRck2g++72R7JBEO1VGZ5cZZQKzk,iv:sOTou2mAZDVmKoBFZd00Wyezt1cSE2etnA5/VTv1OZ4=,tag:DEVVb1MFHMGaeoNDlPDA8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVU0dVS1N0VUc5U2svaUNH
            L3FEVlVkV2x1aElKZTBjTFVnbGI0ZUdsR2pFCnpad3lmZ1IwYVp6eDZsRmRoR05Z
            NVljUW9tdEZ6VGZXWmZFZXBNRzVyQ0UKLS0tIEhkZ1ZOZGU4R05NZmlCVlN3bllV
            TUFwVHh3bVhndFJQVzdESHpNc0Q1ZFkKgP3vrGoEzN6uyDtnDpZghUUo2XEMoQco
            v/pK66TOy+XMoH0lctE6tlnjavOUuRVqeQ/uybLVQLrIDDPjNVEMzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x567hflvyf6w6vt0ynsh36lsckdyp5mufjrz8ndjn7g3kwugrcest2afmt
    lastmodified: "2026-08-28T13:57:40Z"
    mac: ENC[AES256_GCM,data:FxPWLspk4uyrkA2wTAtkzMKEJAX+lCnqhviVetWk65vFuFnIbOCBQXzD4EZ9QFxsNE1g65a4t0T1PjR9pukx00RlbUdU/3uXs6r5aSkJpehbBJhc4dBW4lxbEhq3Xs0jC8GMtnzmq040siowqsx1OxAGiW+PfrAvrqB4ttQTank=,iv:X6fbsuJ9CU6X9w2RQ9Cu/1mEORQO5GYlFkHjo3jwZUo=,tag:+bMsy8CthAIm9jRQaGE5RA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
