apiVersion: ENC[AES256_GCM,data:L00=,iv:fie1PVxlg4sInlTvh4Hr7vB7LuiOPTOh8i4b05Bfw+o=,tag:sBLiGcwN7YL79g+/EXdrfQ==,type:str]
kind: ENC[AES256_GCM,data:zkFK3YHy,iv:5h5hq5pT8ARG9CKnlhFigwiBNlF9qzYyFOz6iZ05Z3w=,tag:YZv+Dpf8xSlfnZAmm4V27w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tY3eYoAfeLhjTxHvEnf6eCkFfhjOXFI=,iv:IXW1wXITCJ4WFhmpHZtDl0+RNNWomzaB0F3SxZ7JdOU=,tag:L/er62Q+RmE6x3HCdW4BPA==,type:str]
    namespace: ENC[AES256_GCM,data:Ysb8W0t3Zr240A==,iv:agy7z2mUSuCEm2hpbLPCGQkDsshflY7YtNcEH62agVk=,tag:pCe0fsM60b0l6n9QayTmag==,type:str]
stringData:
    credentials: ENC[AES256_GCM,data:SGk0cjozX6OP8OxsiAw2CsnX4YL3CA7Iks4mpovAaE/Kd0LQqUqnRdo01w==,iv:xeix9Bw5CEpf/dqayLHnL3xUeFveN6pYuBJXE75hFAQ=,tag:haWEtNGo2alZuw9G+wDoQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VlBacXIzamhYckRHUXB6
            anhpcFRTSTRlajhYVlBMdXdDeVQ5YmNaSlI0CmhhU0plRmR1MVMzUHIxZFV6MXpT
            cTd4UGd2ZzVuQ29HUFFHdGxkRCt1ZlUKLS0tIGQwRnpReEdQcmhSUk9CeHE1dHJQ
            RUpheE9kVWZUZjlTV0dEd3BoUDNNT28KmpEo72BGXTlV0A7QRx8m9kJC9kX2DKKG
            OyW/KCdXgSzU+h4qYaLsc3OX8hmxpsM+aJAONR27zBywtnplq2gaTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x567hflvyf6w6vt0ynsh36lsckdyp5mufjrz8ndjn7g3kwugrcest2afmt
    lastmodified: "2026-08-28T12:50:36Z"
    mac: ENC[AES256_GCM,data:ZJ4bc5WVcll4uPTOSRW5r7BKRsALAIKFVOVZGIqbBiB2szvwJ4KjykxWaVIOQKN58RIBZ0Jg/EErwQxzQB2pLso2TZvm11TCam9cTySn974UO59k14TcUDMIdzfwO0Og6ANj0AY6qp/WtCNtCKUbVbm8ha1KlO/7aO9IV8x+n0E=,iv:Y0PMaV7Aah9en9LTimh293+hURTAI4hJA1PB7brDW34=,tag:ioCn6YUGIksO7ZzE6jYKMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
