apiVersion: ENC[AES256_GCM,data:eH8=,iv:mSTh9o5ETdU5f4NTrRNxiuPO2uvDNb+rO4H3qv/H/o0=,tag:IoiKszA4W+vNeHEzGNBgWw==,type:str]
kind: ENC[AES256_GCM,data:Sl9gICbX,iv:5xMAGkQU4gh2obU32fjSnaIXxjBmMD/n1nwJ/LP8YA0=,tag:z9F0BHGmjLlINRtCXR9qwg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FVeLmpCIYO0RElG7pk3x8SIaMiL7,iv:iKlAtBCm3KTZml3gWgeJB0nU/3qEeT84b2vklksqLzw=,tag:zOZFLQzFhGdmcG8po5rJLg==,type:str]
    namespace: ENC[AES256_GCM,data:SI3XSrXd3JPAdw==,iv:/H3bDevy1EF4cdOD4Ioh6qOM4491MR6lQT/Ot74Gh6I=,tag:Mx2g4kjQJavpgYVwVT6qsw==,type:str]
stringData:
    credentials: ENC[AES256_GCM,data:WhKU7DLaFjbf/hN67Y81PmKfc3fN4WBv0EAOxVWSw6+Xv2JguFPSUtBtuQ==,iv:qOQq+P9nrVlzVlSndBHAkwDL+V8iiYp08LRrYjyEcs8=,tag:Xt9EZPI46gnydSkvOf+7oA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aFJmY3hXSEI5eW5JZjUz
            TXpmWlNOY3dYdnVsUmptOFJJUDVDS2NwSXl3Ci9qRjAxZ1J0ZkliSkJsODZkTkRE
            azZHY1hWL2YxQmZneW9pcTZTbW9qY3cKLS0tIFZzUzBYL1BqbHRGUUh6MmQvcktC
            WFZJc241d3hiYzNSMTFZRjJBUUFBcTgK1yoJwQDxgq/rI6VJPF14N4SiX3GWMZzX
            Tw60tNTB5dgF52MSX4awdN6uuKpfhAHqnWZLiCNXJ9pdPsIhob/dfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x567hflvyf6w6vt0ynsh36lsckdyp5mufjrz8ndjn7g3kwugrcest2afmt
    lastmodified: "2026-08-28T12:50:36Z"
    mac: ENC[AES256_GCM,data:spUA171f081xPdRelf4e23lWcIdOTh7l/l1boQiE1mMI5FboPqQFt9bfvQ4gd8Fy+bkUmJiE37OxlgOzjshSpZW7HeK0+2SokUjkpb7+heibZA0rMfuUDhNsULTZk2qX72or6txukMncABOZOB1j8DrSROLC6N5p1LDVFv1dz3g=,iv:FLqR+qSuY8TJ3rm4MFHHKBrxqsXuq1wcauDp0+Zsksg=,tag:FS/Z3156LEkHIOCG1r+saA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
