apiVersion: ENC[AES256_GCM,data:KTs=,iv:8ocEHoQOTDPXP0AoouG/PlSbG8EWpI5/Hk8vDyOU+9M=,tag:gOoeQjlAp6fhfUq0o3I/0g==,type:str]
kind: ENC[AES256_GCM,data:O9I/G36M,iv:oZ6RUqT2Aeb8P+CGrwfKj3BoNc5buEXtPYHPMfAMgUI=,tag:4rzUdt6ITvuZeweAHFPsEA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8cK5xS+uIvZqmaTFv0SlYm4+UkX1,iv:AJj0GZ2R1n8jwf9S/iJC+tW5eMdwdEfg1+WU4UJ4QeA=,tag:qqmr6lEdh215BLK/KzatnA==,type:str]
    namespace: ENC[AES256_GCM,data:Es+hUB0co1Y2hg==,iv:dEbhnsdZgTIpjErA1s0EO9+XtnQgkn+oKybAHQy/f9w=,tag:KkDaNYoFiAM8XWGeF2vrtw==,type:str]
stringData:
    .htpasswd: ENC[AES256_GCM,data:3I1PYkd/x7VOf1r3dx8GjZADq/D+/0YOgzGJ42PWKdaiANqHumqNX3HMXQ==,iv:kUBn0lKFExSjXk/DVNA36wEaERpMblU3Awua89KP3qQ=,tag:nbMENDlNibVhfUe9GI2g6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Rk43K3BIQ21na2tVWDVz
            U0FTV3Fndi9zS1ZtZ2F2eUlNSCs4Yk5SVEhzCkdYOHlDbVRSODB3cHUvblhIRTdq
            a0lQSWEwSUE2UTdNdE5GS3VnSHBUREkKLS0tIHZnc0grbFo5Ym9rWWRnTkFVZEp4
            bmNwRDRadExDRWxzYkFkdzJiU2RvRWsKoJH5Q2HE1wOtYiLNhaL3rNwbGp65dqjs
            97BebzuR0O1pUtM59CadqOpSlF7VkA1lebAcaVxeIBc2FX2zHflGJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x567hflvyf6w6vt0ynsh36lsckdyp5mufjrz8ndjn7g3kwugrcest2afmt
    lastmodified: "2026-08-28T13:19:39Z"
    mac: ENC[AES256_GCM,data:73SQPP0vVGXbkElHsAUVPJ6PmrC+bfsIceDD4bi6UhUf1JGnz8FNrwgrVSzUM+D4HlpGixOpaTikoZnGavWhrAUw/4D+BW8VHhsXQLjlJVPJWwFd7ssvGSi03PZ5SmAPeCNqH8Ri3lBAmmX4Nc/QimKSyXC4rdh2G6OsyqQ0CiU=,iv:kOkqn80YpIRU/XK9Eo1YxoGrx5nMc8O4nIkGEJ/HplY=,tag:nRfYdxiOR0X20dkLuTv1ag==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
