apiVersion: ENC[AES256_GCM,data:hiE=,iv:C0SmiLAATuBaOd4pofHEoWPSBXKdk/SRPFoZQZE1bvA=,tag:SzAnipvNYL9GijaWS6WMVQ==,type:str]
kind: ENC[AES256_GCM,data:anxD0LRx,iv:u0zBfd1RzBbJCrTGylW8rDhdJpOJxNt26s1Fo95O3Nc=,tag:H4r1gnJ4xHzV6gGHC7H09A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LXzp0CRILbJOq174nPee+x+/8jVK,iv:AGV7hN1kj1zW98bsKJH/87Lmunmq7YiIBHWqm/nbQzc=,tag:dntlitmZ8oPWQmI/5gaRXw==,type:str]
    namespace: ENC[AES256_GCM,data:YBcTcHvCDGWLvg==,iv:utbw+fzbxmhhngK9lG6bIdqT1cRyyGcD1F3Loy859Es=,tag:C5tfs/WVNIwycZ98a+pQYg==,type:str]
stringData:
    .htpasswd: ENC[AES256_GCM,data:4lFMp0OK4tNDzUiIk38Ele+rJqMjSR/YGoo2VcyIplqh1bBAPJ4p,iv:GuONHUAlDeE3mlbJGoimlo68EfgAt0UjQ8yokvXENGY=,tag:oXaPsEIaHoqlfg93TFea3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUFo3anlwY3NnU0VtWkpk
            NDVqUGc4TzhEVTRDVjVvbS9sS0lQSGNreDFzClBFcW5VZmNBbi8zMllDME9zQmN6
            d0dHdHZLcktoZUJHSHNLV2xINUJ0ZVEKLS0tIEVCaDBEZzNpTTc2TExmeXFURUtS
            cWNFNmM3U2c5dFYzOEUxZ1Vmd0dRSEEK/bz7emtG66vZG6Lng4tNuQmEO84srPAB
            8cWSblzYoTGKuNVH96gDrzcBmysFCPRUIhiwQR+MRaS8JReRt8sy5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x567hflvyf6w6vt0ynsh36lsckdyp5mufjrz8ndjn7g3kwugrcest2afmt
    lastmodified: "2026-08-28T13:57:40Z"
    mac: ENC[AES256_GCM,data:lGlw6DUvqXuOopTJ0DIFmU4Th0PQZvGsGGq/GsG/0Xphfre6lbS/l8wxWiZ/Y7Hc2Hj3l57Mi7gWmBadTCYcEO9fpKLIBZuh8wVXDzgRX71//HJe07/g4e65kYidhqYZpLQ4WhaAHxbPQI/mEW5JQW3A44PDMZYcgBq85nDUw6w=,iv:epPATTJFxPfoCT7lO9rMyaFL4kTBjmeApa7XL4pAXp0=,tag:yQoMjmX2Kv/KWAf1r8pfDg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
