apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - db.yaml
generators:
  - secrets/ksops.yaml
patches:
  - path: patch-db-url.yaml
helmCharts:
  - name: job-track
    repo: oci://ghcr.io/robin-vidal
    version: 0.1.0
    releaseName: job-track
    namespace: job-track
    valuesFile: values.yaml
