apiVersion: ENC[AES256_GCM,data:0BY=,iv:o6uv6GAn5qgxfJkeaZnkhS7qwZtWTW6kwWAQ4KBJbIg=,tag:7vbY3RHwhITHFg7XZsQjSw==,type:str]
kind: ENC[AES256_GCM,data:yQsMVE1e,iv:cuETuA+IslOBXZRIVOTQrJvJ2ee2+QfBEEax6dkVTNA=,tag:qisEsFCj+kJXaDNdMalN9w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Bf1lU4ug3PvYQjP1Rng=,iv:bQsVWfmUvWFQQ09wKVO1UQ29uds/BvujycPxWPSExYM=,tag:rgAe4rZhgst3a2WYW87dyg==,type:str]
    namespace: ENC[AES256_GCM,data:j35ybfGE0P4U,iv:9xXmcdZeSG6jKC88wjM+c15Q4c/LAu+p25gQnXpXZts=,tag:kn52cxJrkYreduwZq+QuBQ==,type:str]
stringData:
    AUTH_PASSWORD_HASH: ENC[AES256_GCM,data:KFp62BYVwvjfeXOjpY+QFNl80A3bH/L8VJ16sKeWPFxbpaNl6haVrGIvKVophvxXrO2+PduZbMFs8ZVS,iv:cJFmi2B8guIyt3dOWPSWat1tPgY9ycECfj4RyF4CNK8=,tag:wwFWp36O6W8m9U38fs5L8w==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:p9+Prlrul1JVf8yXnZeMPAIPPVlVVRIa+n6aaTLwRdG9D5G+uGp7rqTaseyph8uYrYZiCAACYQpApzxPmvj7/Q==,iv:GlJmLjda9RM91yJNyatWDr2KuFC6N6kY3m4x9Y6SAus=,tag:2ZftHh1TBerLa8nuvAGk0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydXJObTFjQTEwZ0RRREw4
            bjNvZVF3bFBjMHhTVlRQOGxINzhLUWdKV0JVClFYampROTRFQ3VyV2dwb2o4TzZQ
            MGRGbUE2dDY5QjZYdFlYODhkZUhVTU0KLS0tIEZGZDYyb3p5WHQ4Z3lsVjg2R1pv
            K3kxS0RuUUFRY1VXWEZuemZzVFZTSTQKkXtTqQNge4BcLLE2NyzRqIh+z07M2ohJ
            MWBmXiPWKaH862lNOf33cwifCitESBTP38qLpNUOMHnO5L/8Frc74w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x567hflvyf6w6vt0ynsh36lsckdyp5mufjrz8ndjn7g3kwugrcest2afmt
    lastmodified: "2026-09-13T18:20:43Z"
    mac: ENC[AES256_GCM,data:wnrYrF9iz5SmTRH7p2j/q+Je4BxGblNZCm0va1URESiPNRYzp8gGphY6aDXCkKrKHA6dkrV/8lXKBVh3uk8sB1eO831ACkVT3P603TawqCSpnCcqRCcDxUBCYBKQyKA2P+BjQoucRNGQGtcJx2WbZBF0O0kvp8o0Ndz2qY2P960=,iv:AFLPcb8RwLPe8YUqYxOyF5Bs+O4vVJ1IQCLcjrCitCA=,tag:3FN5vVqkvRDXITYkF2I0cA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
