apiVersion: ENC[AES256_GCM,data:h4M=,iv:H413AqmU4/jUjlkOHHuuxNUPKHbH2NL5MHOEvPmRLt0=,tag:WcsugQqu9tzIHUcjSUCoiA==,type:str]
kind: ENC[AES256_GCM,data:2z+T1CXh,iv:2EXjtOvFc036vtDBDXms/8FYp2QQFEELM/PmXcdwews=,tag:Mhh56aUmrCUuqU/sVtxIpw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:v/kJy/902l1u8Y2qBss=,iv:wou+mNk71voVeFsCVGaMekaspEaIzSq6RiDk5DpCoBQ=,tag:lsYTMwlKwBxLGaioXWyCTw==,type:str]
    namespace: ENC[AES256_GCM,data:H4iv+iy7p1n1,iv:Bb/maX1E9JViiLjvAv8ev0ZAKXOmRA+cJjCxMXiqBfQ=,tag:H45I/VyaO44l9hgCF/yXDg==,type:str]
stringData:
    AUTH_PASSWORD_HASH: ENC[AES256_GCM,data:7pPFeaOiKLicqgcSvPTlqFbXeOhlfZTYrkJOD/hgDVYtO0RKwmi7tp4bBN0D5ZGYenBIJlIYUaZsm+hg,iv:nAi0ohrT42IqhFrDJOmmfVidfskelBfTXhqbU5ezbz8=,tag:ttZjCVCEy6XbFeen04wJ4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjU3pGZmlFT1I4SkV1TElo
            VDFFbW0wbjEvTU9tZmRQc2ZkQnRMZ01jUWpnCnpvVGVjODJSY3daMmh1a2dqVlU1
            c2JubEdoZlVuTGFTN2hEL0VJSHBBWm8KLS0tIHNFRGV2d2NLVWVzeTdvWkE0c2JS
            V1dpU3JHeUpMZUZYdUlpTHk3TEk5Z3MKyOTzJFgSzF7CygLAoTphAuVeuUWTn39g
            DS+z/dcUaVlA2IvcdgeVKXzDZAFP/r5waN1jzDFB+d93VwyRmN1ppw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x567hflvyf6w6vt0ynsh36lsckdyp5mufjrz8ndjn7g3kwugrcest2afmt
    lastmodified: "2026-09-13T18:18:08Z"
    mac: ENC[AES256_GCM,data:cNE9wksyylpY3eq2Eh70nj+2k/fD3fnDMM5HX5I2NubDSpWU7TkfY84i6YYKJfL40rHiPXxhYq2Xek3bBerEMOvZIp4AQV5LzojmRrquJIbv6Z6r9Q2O+mSDegJinopcrLFfrajJmV4dCKNjPwivR+bWuC/iDv8gpe2Actfx+kA=,iv:BsiIUB1vZey9uX1R0Y/oalh2SAcs8SiXRx4pbbQ8D04=,tag:Y0c2RzuKwt1AIB2kB5LdaQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
