apiVersion: ENC[AES256_GCM,data:GIA=,iv:mulWBh0hGpDpK3ErsMSKqBrVf3rLAsl8Jh29YM9kh0U=,tag:rsF9fRcGsGaBJr+UbSH+bA==,type:str]
kind: ENC[AES256_GCM,data:N9QVAuPM,iv:85gtwUjGwVkbGodndr8ZRDLTQTm/U+6djFWX5mEPY3I=,tag:BHbYj5Y/EOVkAgyvJrFgSQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fse2USoiBrIlq6YVIrc=,iv:Yv8A+rYvS5QlNUYVF/PkmWB+0QbFyDW1vK1t/l6ypxY=,tag:z/y3YL/xqSkTW9cJsZB27w==,type:str]
    namespace: ENC[AES256_GCM,data:lWy7XNNzLvFG,iv:xfwyfujcbkF0g+tz4ytjW5Tts6RiegICxJSnVFxPCDQ=,tag:8UFMKFfXL+BAzxnk3H8siA==,type:str]
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:0hWOFD6m2bHoHS1z/cwj3NR2lCiYBnyYy4edTyW1Sa7aREdHMk1sJLEVcdynIcRowoWGeiTzFFaPrSpYVuM=,iv:C1NjZ3s3bOnJvyzzqo62az9rQUADg0p/yq+C4/nVnTU=,tag:ydtJSUj0PYzZcmOrC6/05A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Rm9HNWwwbGZLSW0xK3Az
            T3pIVDdnNCtmWU96M085QUV2WjExS3Qxa2xJCmxhUDhKVlJ4Y3YxWUsvQjRxRFVJ
            ZEZxbVV1OE9SMlkrcUlPTGdUdUU1SE0KLS0tICtPQmJhbmpHNU5LUUdMTVVFWDFl
            bWJRc3YrM2VyeFZaQXlMZ0pJYUVFcGcK5ATzw1k7eXFM1C5PZHvUapjTj9YZM4Mz
            RNxvd0w1g9MIfR4B45WDtoI/peN1m//9hk+l2xZ9UCJuMc6FX0psUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x567hflvyf6w6vt0ynsh36lsckdyp5mufjrz8ndjn7g3kwugrcest2afmt
    lastmodified: "2026-09-13T20:44:36Z"
    mac: ENC[AES256_GCM,data:jKDh7WugTvSSgPYdSIjyHuhHcuavIgUhSck6caWknw0p4wBVXYImioBr8MvieiP+P/hcGtHIIArWPO1dAW+88umjBApG90aDiV4x4zYPLFR+7M4sTPeqW5zQJ2godhXEukNKzhqK4I+yO9fqS4xuYe3Q3zcWLRHtiQlMZ8srJf4=,iv:3K5BsWdWKdDqT2IVwqu4sM7nW2ZOwZOdEMLU67AfzOg=,tag:1pSmq8/KbYIqhY/+gVDMzw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
