apiVersion: ENC[AES256_GCM,data:E/s=,iv:NPiC6Neiz+bey3wJ5YTXiQfVWem3Qw4gwGgsES7PmQQ=,tag:I6xHVVSIuki+sUlH6qas5A==,type:str]
kind: ENC[AES256_GCM,data:ZJy4rhqG,iv:oqt9QONHKPuNkOXmxzn+GvAfJYus5oOEx4JhVwsCgfA=,tag:tv5E5dDViMPva5mHCcaF/Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1dvAXwBxC8bJkdK01hwgXQTyPrZTnNki2sJNsw==,iv:8q9iCy8Snlkl0l6YIwxoBigkwxMeR10HOn5ib40Q/sc=,tag:C3sJ23+eMj8oTWOGwaCloA==,type:str]
    namespace: ENC[AES256_GCM,data:fDXipDL2,iv:aQJoNj1gifc/0QVelqrFraZhhAMoh6ZRMX9BbqF4eok=,tag:utlEsYXzPmzp2waacX6PTQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:2XSpd6M=,iv:MDTau1NunM8Dp22X5B+q4Ju4Bv2crpxumIbAV6MCxvA=,tag:iJmAYawk+/NIt70D/FWpmw==,type:str]
    password: ENC[AES256_GCM,data:UIe2cN5F0z/J4FAAVX4=,iv:tO7jbLmhzOfyWuv1SLXb8wVJBSFqhwC86sJ+lw6igdM=,tag:ZmfUWleNeyAZNeYNm/zpkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RjBRU1hXaXR4eklKZGx3
            MjQrZG1xTTh6Mmp6RkplaWowZWQyMkppRFY4ClpPdGovdWRJMDA5dzFmNDVQWEpS
            dTRNaUZ0QWRRZ096T0xOQXdNTkRYQTAKLS0tIExsVnhtems5U09weTZ2ZE02ekox
            NGZXS01hZUV5VWdYMFZhTitYVDR0d3MKuvB0aGKYBmv3y26hUtl07FBXe6Vp0Ka7
            OWYDxyzz27ESAm3Fs4Fs3s7G8nR/U2MjDZHyuJeRfNFLgh0x3XTRRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x567hflvyf6w6vt0ynsh36lsckdyp5mufjrz8ndjn7g3kwugrcest2afmt
    lastmodified: "2026-09-20T19:20:39Z"
    mac: ENC[AES256_GCM,data:o1pq6PfkNLnTlwxdJeNeUj8D7m1KktxDvNkG/qoZCK+CGl5PVTHYncdBspfu0HaPG1O3wdrrcpUe/7xGr+CMrHdi7eXnoHyOFRdR5k8/8IUKzPB16xjrTBJIURAGWLlBFY7xuspbtJ7eZknDaVDo8/b78ZruRMke0UDjMFWIf3Q=,iv:qJYnejQksvZacUpF9SCKAE/ShRyq6By53x7W85ijduE=,tag:nxevTEg+4veEblWPql8JIg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
