apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - httproute.yaml
helmCharts:
  - name: personal-site
    repo: oci://ghcr.io/robin-vidal/charts
    version: 0.1.0
    releaseName: personal-site
    namespace: personal-site
    valuesFile: values.yaml
