configs:
  cm:
    kustomize.buildOptions: --enable-helm --enable-alpha-plugins --enable-exec
  params:
    server.insecure: true

server:
  ingress:
    enabled: false

repoServer:
  podAnnotations:
    reloader.stakater.com/auto: "true"
  volumes:
    - name: age-key
      secret:
        secretName: argocd-age-key
    - name: custom-tools
      emptyDir: {}
    - name: cmp-ksops
      configMap:
        name: cmp-ksops

  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4.3.2
      command: [/bin/sh, -c]
      args:
        - cp ksops /custom-tools/ && cp kustomize /custom-tools/
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
    - name: install-helm
      image: alpine/helm:3.16.4
      command: [cp, /usr/bin/helm, /custom-tools/helm]
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools

  env:
    - name: SOPS_AGE_KEY_FILE
      value: /etc/sops/age/keys.txt
    - name: KUSTOMIZE_PLUGIN_HOME
      value: /usr/local/share/kustomize/plugin

  volumeMounts:
    - mountPath: /etc/sops/age
      name: age-key
      readOnly: true
    - mountPath: /usr/local/bin/kustomize
      name: custom-tools
      subPath: kustomize
    - mountPath: /usr/local/share/kustomize/plugin/viaduct.ai/v1/ksops/ksops
      name: custom-tools
      subPath: ksops

  extraContainers:
    - name: ksops-plugin
      command: [/var/run/argocd/argocd-cmp-server]
      image: viaductoss/ksops:v4.3.2
      env:
        - name: SOPS_AGE_KEY_FILE
          value: /etc/sops/age/keys.txt
        - name: KUSTOMIZE_PLUGIN_HOME
          value: /usr/local/share/kustomize/plugin
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          name: cmp-ksops
          subPath: plugin.yaml
        - mountPath: /etc/sops/age
          name: age-key
          readOnly: true
        - mountPath: /usr/local/share/kustomize/plugin/viaduct.ai/v1/ksops/ksops
          name: custom-tools
          subPath: ksops
        - mountPath: /usr/local/bin/helm
          name: custom-tools
          subPath: helm
        - mountPath: /tmp
          name: tmp
