apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-robin-vidal-com
  namespace: envoy-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretName: wildcard-robin-vidal-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "robin-vidal.com"
    - "*.robin-vidal.com"
