apiVersion: ENC[AES256_GCM,data:epM=,iv:c2OTagBtSbMsxdETTcM+1mQQK1DjK7/yWILIjEVjC1k=,tag:NxFQXVeTP8eIUQbZjgRiww==,type:str]
kind: ENC[AES256_GCM,data:StD1dC93,iv:/mWc+HezCfTakjuvvlFHfXBSL2sWfcpQHiH6z+4tnOs=,tag:v8furdJwuA3Vv0cxokeiFQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MqTyN9nHxdMvopFmqg==,iv:LoWL3n25IfyNQ/5Dhny7Q0PNaQAntrr3Km69QK8E6xM=,tag:soJFRjX3GeS6/IHRaUSIPA==,type:str]
    namespace: ENC[AES256_GCM,data:8n3LijcN2TS2vw==,iv:iEQogIQ1gjeXGlV0J6w4FI0CJXSZKR6YaBvxtgP/mfU=,tag:lbOnwY69Ige+rJNPImrB5Q==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:Ss1Mlog=,iv:bUzaUUCr9+W4TTwC+vFNrE4Z9HKHXBXvGnLJtLKS32I=,tag:5W9ajsEatQv6NhreyNlFzA==,type:str]
    admin-password: ENC[AES256_GCM,data:aY14dkFXRqmOH3VsSwc=,iv:cg2HENvlMWy+LXnuHL2nVA7V1JLHxG5etmlcrHc2HWQ=,tag:2SoPlJFvhWIuibjKneslCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQlkzVjFXMHVBVGdraGRs
            V3doSmpjdG1oaCt6N1oyejZ1aUxrYmhpVXpnCmIvNjVXYkQ0QkxLUVM2ZDJqYnRY
            SWpvUE5aQjhmU25lUDdqblVXWFptV2MKLS0tIFVKQ0srT3g1b3Ezdm52MUJlK0Rm
            N2Z4YmtSanIvbEliSDMxQmh0dlZHc2sK4VnoyQiHQOgtNWcqN2ZUH6BETA4BvWgK
            p11pQQcvW1rhpqcgqv+jojOZVlV2W12QHqYLJcZ6N3J6yb78pcMhYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x567hflvyf6w6vt0ynsh36lsckdyp5mufjrz8ndjn7g3kwugrcest2afmt
    lastmodified: "2026-08-28T12:40:42Z"
    mac: ENC[AES256_GCM,data:cbUKg/iv9imvic7SRDVrh6Mjc7nnDATtylT9YnNfl5gkm+svbJDYSpV6DRAlxFdTqcfFjiQQFIedS++mTjDYdI6vwwdb0BSF+4If/Cvmai0+CNrW/ClX59UpI7YYiipcT2JxmY8b5b1GVdsYQu8st+Gjy8Fdv7HwdjaUfGALV08=,iv:TKalx6msPtBzLrLcQ9fGGXPuEeBE6+ASVHl7Yhuc0Ck=,tag:XJMd4Ul8/SJmaFH1YnTjaQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
