nextcloud:
  host: cloud.robin-vidal.com
  phpConfigs:
    uploadlimit.ini: |
      upload_max_filesize = 50G
      post_max_size = 50G
      memory_limit = 1G
  configs:
    trusted.config.php: |-
      <?php
      $CONFIG = array(
        'trusted_domains' => array(
          0 => 'localhost',
          1 => 'cloud.robin-vidal.com',
        ),
      );
    proxy.config.php: |-
      <?php
      $CONFIG = array(
        'overwriteprotocol' => 'https',
        'overwrite.cli.url' => 'https://cloud.robin-vidal.com',
        'trusted_proxies' => array(
          0 => '10.244.0.0/24',
        ),
      );
  existingSecret:
    enabled: true
    secretName: nextcloud-admin
    usernameKey: username
    passwordKey: password

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  host: nextcloud-db-rw
  port: 5432
  database: nextcloud
  existingSecret:
    secretName: nextcloud-db-app
    usernameKey: username
    passwordKey: password

persistence:
  enabled: true
  size: 50Gi

ingress:
  enabled: false

startupProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30
  successThreshold: 1
