apiVersion: ENC[AES256_GCM,data:+ZQ=,iv:VIhtcAPlYvlZ0+SUT+z8sYlIf+P92Y5Ek7u5C/J0yM8=,tag:UqbjVjlAekR7kN+6FLZjRA==,type:str]
data:
    sshPrivateKey: ENC[AES256_GCM,data:IBtUF8VP2PHVozlb5YCFw73RlayVhvZc2GqqfVuF/LTpcRIKLDmVAZ5WCaSgkcBiA0mTaoYe4LsPbus0sf+lQLdLDyFttT1r+SXkck+kRNZDxvse6Gr13FOGEH1itih3RpRQIAPdeILmO8fYIxa8IN4CF4bWwaqJcHJBvA9J/lDOCEOo7txE7hpoiKeZBbyYHGM56kw5u+pHT2Ez1E2VAWEtdlIsPAN1bq024iThbT8u1Dz8c1jqfRWfKFjKawA8YSKhCfokSxAvsfM841NHiso71W2HhFIVc/RYy16hxtg7oTH8y0NUuHiEuVdQ7Xo/L6T8fvdxnLnWcWzmuhl0uARbpQ5paHMlS63riKlUbejX0lg3eSaUTEiJ/FfJPk5zkZ+RAmZTb7LtXe0VbHvU15i+fDLd0eFoZfFfV7egNALMF/AoXI74XBeT/02BJkZ8DkswsEM3G7AT8iXqpvc9ybLPyP5n4ZNcsGwox8hqZrU+99qUofI8KSjv7bS14WdrFdbZpwvmEtgllK62fAm5NcFc6JBfl7f0t1Hk9/yQsF1NBsyGnkM7xfu8evrUlHPKA9NHcI+nmVbeEHp10B+rtfyOQlm4KkuvHa/Dv/6+97yFTHjaRdMMT9cCU22+nl4gJ4yHKj9C6yYYPxRzJjpSkWZBtL55qphAGzT7mw1wCTzKhXBmE+jcgLqsKIP07dy3nzM+Pe07QL4hwkPCUeg5EvBUK9Y=,iv:wImao2ZgakxPEOi259MZEogD5Qy04a7/4/ANI953oaQ=,tag:/d5IfP1/DSFST4VPJLI/zg==,type:str]
kind: ENC[AES256_GCM,data:fMNME3g5,iv:daivtozaxlSNJnau4U0nPgXfJNZrbKHqbBepJuTdNak=,tag:+VnStbIBxFfi6vBArV4p9w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+nBYXz31HKAuJjzV9d7aD6N3iqayj8sW,iv:2KKjWZJ4b08fYSlUK4NceBLVk37iwvC1V8gEFyCzZKA=,tag:rTF1oLVpkhAsSylJqOvcpQ==,type:str]
    namespace: ENC[AES256_GCM,data:xxEIt7+t,iv:O/UUX133Txeiks6pJLcXBvdbSAuManLj6oISLOax6HQ=,tag:rP2gNVbuAl9btiqObIbO7Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTWFrTllTYmErNStCZzM5
            bW5xUVFSWXp0eTNmeXNUaWFlem8zVXFxSDI0CjNicjJ2M2xFSjF2eWxQT0laS214
            b28veGRPSDQ2TitpZGVxenZ2SjBqcTAKLS0tIHZLZzQ3TUdrd21QRmgvRkVGZWxW
            M0FienpkcVpBcGJNTEJHTVUvaWhFUDgKROPuFBpC741NRvot7rZmc7HKxhefaOb2
            L4Y+5s/kCkNf5cQJhNvoob8Ww0FmqLJ3pbgqSYT2mKTIcVRT4h1MFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x567hflvyf6w6vt0ynsh36lsckdyp5mufjrz8ndjn7g3kwugrcest2afmt
    lastmodified: "2026-09-20T18:56:06Z"
    mac: ENC[AES256_GCM,data:997eS5KzXnBgpc2CnjRaIK1w+iL+DB5HEjupdcJIgMu3cpvgC5g1di/7/vf4ZJ/zmhCh7OGNVIEg8cQ545AVtalBs5ucQdlIrCctsPWxZ8CuO3QFN1j7+uGYqCi6fyDIH9ho+rgslXT83R4ot09oZbHmk6blhC3bBujB6XoHN+c=,iv:ISLZENJ7wFaohQJh4SHeKqBe3+J8Z9v6UTKSYNTco0Y=,tag:gRB6ao8q18coZalQx9zskA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
