apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-ksops
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: ksops
    spec:
      generate:
        command:
          - sh
          - -c
          - kustomize build --enable-alpha-plugins --enable-exec .
