apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true
  argocd.argoproj.io/compare-options: ServerSideDiff=true
helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: 0.29.0
    releaseName: cloudnative-pg
    namespace: database
