apiVersion: ENC[AES256_GCM,data:Lh8=,iv:XskRf4lC5H+6S8Ufwagvp2rYgBS2VEKNd6cowwdELmE=,tag:ZmO1YDkBHJ9owmiYwx+f+g==,type:str]
kind: ENC[AES256_GCM,data:pfxcSzt/,iv:wqnviPmFMYx5X6IEjO535yOIsdT+x8nkuyNGdO2goe8=,tag:li4bmK1AvZ3M3LZztVWGsA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:d0pyUnMmlHpNg8qCRSWN+FS8wUI=,iv:PR7uw0tUjiKxiHJB6QvzxZz3bmC/gOuM0p1DwVwyC3U=,tag:tbyJil1wN7ixhErrndmLtQ==,type:str]
    namespace: ENC[AES256_GCM,data:ddcG/jMK8yU8AAFY,iv:KFrf45k6qeBIVlz32+08Pfx1BozYuV3eUzEMb3dHOZs=,tag:qQQsCGPzG76WHk4d3+JGNA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:gfKts5U42jxIM8dhEo+Lj5BcF7LLHnxE7lHFLdA5YIVe2ojXERsclY4gxGR10KBtvCJjNuk=,iv:f6IZW5woy8qYktP5rAeKH8W3+Fl1OrJrHrTyODnmI18=,tag:kvNnAUlXd5OJZqEMTLLqjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaE1uM3ZKbmxaTlYza2lP
            RUZnb1FwUTk0a1o4c1pmZVNWSmRsWHlDQ1hRCmFldDZTZHpZQkxPUXVxZUZmMURQ
            VU56eWV5aWs5eGcrbTh3bUxVckZQb0UKLS0tIGNwUEVnZk9KMDZUWmdidW1qem1Q
            QVJidncvOGhlVUw4alRqY0YvYVlMRHcKGjLRjMNNGx7cesKgQq0tg/KuXfpljA+8
            aADKTRNgrN8D+qZoLREvSe6C479u3saik5FyLB9s1b00IxS7duZoig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x567hflvyf6w6vt0ynsh36lsckdyp5mufjrz8ndjn7g3kwugrcest2afmt
    lastmodified: "2026-08-27T14:51:13Z"
    mac: ENC[AES256_GCM,data:/W22ix3rFgikIG4u5fRpOT9SEkZzEX9/VvBlb/V8G/wlw2hMgMCn6lU9t4LEwTotau2DL1H6vJ+LyNrwR6A3v2ICHL+vYe+dftjlHvGduCdAcL+z9CL5s9v1Y1g3AuGffGevS6ceb7KpdZPl3K/POSdWUVFs1H6v/fK7wjoouWY=,iv:n5u3fD6EYq/wJBZBmwWeUv3rNvSxNRQJ2/SVT+i66V8=,tag:etMG8HDSAoklA5p7mADnvg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
