apiVersion: ENC[AES256_GCM,data:Ib0=,iv:SGHvhcb9feJH76IZMANWXEQUTf8Y9hmE07kGpm8rDm4=,tag:g/Li2OLjYhydMgWukIj3Jg==,type:str]
kind: ENC[AES256_GCM,data:fExZDQGG,iv:iFtph6dPKa6lI8cyE516+i5KuCUE1G2a22WrVMnlbgA=,tag:CI2IMPUZ9nKgDHgDiFBw4Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:L6OQQNgYp25UIgzGR/T5G54=,iv:7uREB71X+P9XlZNAvyL2Ruf4stQsD/2wu8SE6p1tg+Q=,tag:V73q+Uu95Izqji5R6UTdtg==,type:str]
    namespace: ENC[AES256_GCM,data:H2ewKXfNHMq90eI=,iv:lUZTdkrHpjGQuLwqYXlyn6spAshBy76ZhIPu63IuGvk=,tag:etotIvFKUbhBjAPFLzpliw==,type:str]
stringData:
    admin-token: ENC[AES256_GCM,data:H5E7mjy77V4kcczsHDc=,iv:xSpY4t3WocmMxoYTVMCEHOsvjgzX8DfKtAI91eko/9Y=,tag:tvhosJ8q73HmOiPpkkTiKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOEY3cGthb25GcnlSZjMx
            dWVQeld4UklOZkJ1SStQU0ZpOEVXdG00SlM0CklUK0xtRnZLOTBDa3pBblFKYUVz
            bmVzbEorbGhnL0MvVEVKNy9McWNCdEEKLS0tIGdBTndzQUZoTzlxZzJtQUtSQXFX
            ME9Fa1RheFQzWHpJaVhnK0RHcTZielUKiTFwtZnxeGBWrfuGnqi0tUSsvm4WSiVo
            /Pes3TCZ3uLle/dBuDetPTOJLzhpdWBpoM+PDf08w9XBy9/Eg9BX+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x567hflvyf6w6vt0ynsh36lsckdyp5mufjrz8ndjn7g3kwugrcest2afmt
    lastmodified: "2026-08-26T13:51:58Z"
    mac: ENC[AES256_GCM,data:y0FDfNVTMOtFPP/UtAj4U0jzkfG828ZfU7gewobJ8AM0/rxD1zTD1RN4KRvV9A7ePAyUetyXDGGn5L0j4qLWU9ifYLtdjRT34YAzg28AdAO3H9L/LAjp92PTLSBTNYX/hFOF4w3eAAgeQeGI1T+wbFoGdvx1OSXgl56F4YVYfX0=,iv:98uVNwaQfRt7Iz56tuZU002pDd42Id2HFSknfsvNSvM=,tag:FD0E/p/H74zgPhN2/kEkNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
