apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: neetrack-db
  namespace: neetrack
spec:
  instances: 1
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: neetrack
      owner: neetrack
