apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - db.yaml
  - httproute.yaml
patches:
  - path: patch-db-key.yaml
helmCharts:
  - name: neetrack
    repo: oci://ghcr.io/robin-vidal/charts
    version: 0.1.0-sha-2ab9903
    releaseName: neetrack
    namespace: neetrack
    valuesFile: values.yaml
