apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-helm
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/robin-vidal/homelab
        revision: main
        files:
          - path: "kubernetes/infrastructure/*/helm.yaml"
  template:
    metadata:
      name: "infra-{{name}}"
    spec:
      project: default
      source:
        repoURL: "{{repoURL}}"
        chart: "{{chart}}"
        targetRevision: "{{targetRevision}}"
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
